name: Continuous Integration

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
jobs:
  code_coverage:
    name: Run Code Coverage
    runs-on: ubuntu-22.04
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9
        - uses: Gr1N/setup-poetry@v8
          with:
            poetry-version: "1.4.0"
        - name: Install dependencies
          run: |
            poetry install
        - name: Run Code Coverage
          run: |
            poetry run coverage run -m pytest
            poetry run coverage xml
        - name: SonarCloud Scan
          uses: SonarSource/sonarcloud-github-action@master
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}